name: Test

on: [push]

jobs:
  test-generate:
    name: Test generation
    runs-on: macos-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: x64
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Download model
        run: make download
      - name: Generate
        run: make generate
